export const projects = [
  { slug: 'meshline', name: 'MeshLine', type: 'Offline-first P2P mesh chat', year: '2026', color: 'blue', description: 'A serverless progressive web app for decentralized peer-to-peer communication and local-first information sharing during network disruption.', stack: ['React', 'WebRTC', 'IndexedDB', 'PWA'], github: 'https://github.com/Karthik-Sriram-11/MeshLine', statement: 'Offline-first P2P mesh chat', architecture: 'React PWA · WebRTC peer mesh · IndexedDB offline store · Leaflet safety map', challenge: 'Make nearby communication and information sharing resilient when the internet is unavailable.', solution: 'A gossip-based propagation mechanism relays multi-hop data between connected peers, while IndexedDB keeps essential information available offline.', next: 'Strengthen peer discovery and add richer recovery flows for interrupted connections.' },
  { slug: 'medvault', name: 'MedVault', type: 'Encrypted medical records, done right', year: '2026', color: 'violet', description: 'A secure medical records platform with role-based access, digital identities, and encrypted document sharing for doctors and patients.', stack: ['Node.js', 'Express', 'MongoDB', 'JWT'], github: 'https://github.com/Karthik-Sriram-11/my-health-hub', statement: 'Encrypted medical records, done right', architecture: 'React client · Node/Express API · MongoDB · JWT role-based access', challenge: 'Let patients organise and share sensitive health records without losing control over who can access them.', solution: 'Dedicated patient and doctor workflows support uploads and record sharing, with temporary, time-limited, and revocable permissions.', next: 'Add audit trails, stronger encryption at rest, and better interoperability with clinical systems.' },
  { slug: 'codeclash', name: 'CodeClash', type: 'In-browser coding arena', year: '2025', color: 'cyan', description: 'An interactive coding platform with timed HTML, CSS, and JavaScript challenges, difficulty tiers, and real-time leaderboards.', stack: ['React', 'Node.js', 'MongoDB', 'Sandbox'], github: 'https://github.com/AAC-Open-Source-Pool/CodeClash', statement: 'In-browser coding arena', architecture: 'React interface · Node/Express application layer · MongoDB · role-based host tools', challenge: 'Create a fair, engaging space for students to practise frontend skills under real competitive constraints.', solution: 'Timed challenges, beginner-to-advanced difficulty levels, live leaderboards, and separate host-participant flows make each contest manageable.', next: 'Expand language support, add participant chat, and improve mobile competition flows.' },
  { slug: 'gst-filing-agent', name: 'GST Filing Agent', type: 'AI-assisted tax workflow', year: '2026', color: 'orange', description: 'A Micro-SaaS agent that turns invoice photos into structured GST filing drafts and filing-ready CSV exports.', stack: ['Python', 'Streamlit', 'OCR', 'Gemini'], github: 'https://github.com/Karthik-Sriram-11/Micro-Saas-Gst', statement: 'Invoices in. GST-ready data out.', architecture: 'Streamlit interface · OCR pipeline · Gemini Vision API · CSV export layer', challenge: 'Reduce the repetitive manual work of extracting tax information from invoice images for small businesses.', solution: 'OCR and Gemini Vision extract GSTIN, HSN codes, tax values, and invoice line items; classification logic prepares B2B/B2C GSTR-1 data for export.', next: 'Introduce human review queues, bulk upload support, and integrations with accounting software.' }
]

export const skills = {
  'Languages': ['Java', 'JavaScript', 'TypeScript', 'Python', 'C++'],
  'Frontend': ['React', 'Vite', 'HTML', 'CSS'],
  'Backend': ['Node.js', 'Express', 'REST APIs', 'Auth / JWT'],
  'Data & tools': ['MongoDB', 'MySQL', 'Git', 'Docker', 'Figma', 'Postman']
}
